language: ruby
cache:
- bundler
before_install:
- openssl aes-256-cbc -K $encrypted_80bf4ea4886d_key -iv $encrypted_80bf4ea4886d_iv
  -in certs/pvt_key -out certs/gem-private_key.pem -d
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-aws.gemspec
- gem install sensu-plugins-aws-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: fOoSlWtNlFaSi+Ncn1BqtZbq4LgcNWlYk4kuk6zpXaJt4fMfibU6qTIqbxsJPGbQIC9A86yu0tyAh8Te/uIKwIUK9/KhrunH1KnBgfLmryoJtZyUC4SlPnr+HcnzP/Y8kko7Rs9G+qO/a26wp1e9PyiK92djqakDF3SSpGO5bZQ=
  gem: sensu-plugins-aws
  on:
    tags: true
    repo: sensu-plugins/sensu-plugins-aws
    all_branches: true
    rvm: 2.2
